### ISSUE TITLE
failing on bundle install

### ISSUE THREAD

**Issue by itgeekygirl007** [pentestgeek/phishing-frenzy#326]
getting the follow error - thoughts to resolve?
bundle update
/usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 13 total gem(s) (Gem::LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'

**Comment by itgeekygirl007** [comment]
I fixed it :)
