### ISSUE TITLE
Failed to start sidekiq.service: Unit sidekiq.service not found. 

### ISSUE THREAD

**Issue by mantis-le-sin** [pentestgeek/phishing-frenzy#379]
Hi guys,
I was installing PF using this howto: https://www.phishingfrenzy.com/resources/install_kali_linux
I have an issue with SIDEKIQ and when I try to browse PF, all I can see is the Apache default page.

**root@kali:/var/www/phishing-frenzy/config# bundle exec sidekiq -C sidekiq.yml**
No such file or directory @ rb_sysopen - ./log/sidekiq.log
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:711:in `initialize'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:711:in `open'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:635:in `initialize'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:353:in `new'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:353:in `initialize'
/usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:39:in `new'
/usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:39:in `initialize_logger'
/usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:348:in `initialize_logger'
/usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:40:in `parse'
/usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.1.4/bin/sidekiq:11:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bin/sidekiq:23:in `load'
/usr/local/rvm/gems/ruby-2.3.0/bin/sidekiq:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**root@kali:/var/www/phishing-frenzy/config# touch ./log/sidekiq.log**
touch: cannot touch './log/sidekiq.log': No such file or directory

**root@kali:/var/www/phishing-frenzy/config# mkdir ./log**

**root@kali:/var/www/phishing-frenzy/config# touch ./log/sidekiq.log**

**root@kali:/var/www/phishing-frenzy/config# bundle exec sidekiq -C sidekiq.yml**

root@kali:/var/www/phishing-frenzy/config# service sidekiq start
Failed to start sidekiq.service: Unit sidekiq.service not found.

any idea?

**Comment by mantis-le-sin** [comment]
found the issue. I was not in the right folder.
Following the how to I was in /var/www/phishing-frenzy/redis-stable/utils.
To launch the command I need to be in /var/www/phishing-frenzy

probably the howto need to be modified :)
