### ISSUE TITLE
Please assist

### ISSUE THREAD

**Issue by Stonecode97** [pentestgeek/phishing-frenzy#406]
ake aborted!
NoMethodError: undefined method `new' for BigDecimal:Class
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/duplicable.rb:85:in `<class:BigDecimal>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/duplicable.rb:80:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object.rb:3:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/configuration.rb:2:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/configuration.rb:2:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/railtie.rb:2:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/railtie.rb:2:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/engine.rb:1:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/engine.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/application.rb:7:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/application.rb:7:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails.rb:11:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails.rb:11:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/all.rb:1:in `require'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/railties-4.2.7/lib/rails/all.rb:1:in `<top (required)>'
/var/www/phishing-frenzy/config/application.rb:3:in `require'
/var/www/phishing-frenzy/config/application.rb:3:in `<top (required)>'
/var/www/phishing-frenzy/Rakefile:5:in `require'
/var/www/phishing-frenzy/Rakefile:5:in `<top (required)>'
/var/www/phishing-frenzy/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

**Comment by Hosted-EU** [comment]
There’s a new Phishing Tool Out There!!
It’s able to capture cookies to bypass 2FA ✅

Watch Video On How It Works : https://www.youtube.com/watch?v=Bgu4JtCwtX0
