### ISSUE TITLE
Web application could not be started

### ISSUE THREAD

**Issue by atheriqbal** [pentestgeek/phishing-frenzy#407]
Hi, I am following this link https://www.phishingfrenzy.com/resources/install_kali_linux but I am getting the error in the title. 

Log in browser:
Gem::MissingSpecVersionError (Gem::MissingSpecVersionError)
  /usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:309:in `to_specs'
  /usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:319:in `to_spec'
  /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_gem.rb:62:in `gem'
  /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:73:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

Any response would be appreciated.

**Comment by atheriqbal** [comment]
Now I just get a page of files/folders that are located in the public folder. Checking #248 .

**Comment by atheriqbal** [comment]
Now I am getting this.
![image](https://user-images.githubusercontent.com/23431134/124223898-11426d80-db1e-11eb-9972-562ffa64f569.png)

**Comment by Hosted-EU** [comment]
There’s a new Phishing Tool Out There!!
It’s able to capture cookies to bypass 2FA ✅

Watch Video On How It Works : https://www.youtube.com/watch?v=Bgu4JtCwtX0
